version: '3.8'
services:
    backend:
        build: 
            context: .
            dockerfile: packages/backend/dockerfile.dev
        image: modulist-backend
        container_name: modulist-backend
        ports: 
            - '3001:3000'
        volumes: 
            - ./packages/backend/src:/app/packages/backend/src
    frontend:
        build:
            context: .
            dockerfile: packages/frontend/dockerfile.dev
        image: modulist-frontend
        container_name: modulist-frontend
        ports:
            - '3000:3000'
        volumes:
            - ./packages/frontend/src:/app/packages/frontend/src
        environment:
            - CHOKIDAR_USEPOLLING=true
        tty: true
        depends_on: 
            - backend